- name: Upload to Codecov
  uses: codecov/codecov-action@v4
  with:
    # token: ${{ secrets.CODECOV_TOKEN }} # optional for public repos
    files: target/site/jacoco/jacoco.xml
    fail_ci_if_error: true
